# Generated by Django 3.1.1 on 2020-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
                ('publication_year', models.IntegerField()),
                ('authors', models.ManyToManyField(to='webapi.Author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
